language: php
os:
  - linux

git:
  depth: 1

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

cache:
  directories:
  - vendor
  - $HOME/.cache/composer

before_install:
  - composer selfupdate
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;

install:
  # Install composer packages, will also trigger dump-autoload
  - travis_retry composer install --no-interaction
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --bootstrap tests/bootstrap.php tests/

after_success:
# Submit coverage report to Coveralls servers, see .coveralls.yml
 - travis_retry php coveralls.phar -v
# Submit coverage report to codecov.io
 - bash <(curl -s https://codecov.io/bash)

notifications:
 email: sk@xbug.de

