language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/

notifications:
 email: sk@xbug.de

